apartments = [
  {
    address1: "123 Main St.",
    address2: "Apt. 43",
    city: "Butte",
    postalcode: 12345,
    state: "CA",
    country: "USA",
    managername: "Alex",
    managerphone: "(123)456-7890",
    managerhours: "8am - 5pm M-F",
  },
  {
    address1: "456 East Rd.",
    address2: "Unit A",
    city: "Butte",
    postalcode: 12345,
    state: "CA",
    country: "USA",
    managername: "Alex",
    managerphone: "(123)456-7890",
    managerhours: "8am - 5pm M-F",
  },
  {
    address1: "789 Sheet St.",
    address2: "Apt. 9",
    city: "Butte",
    postalcode: 12345,
    state: "CA",
    country: "USA",
    managername: "Alex",
    managerphone: "(123)456-7890",
    managerhours: "8am - 5pm M-F",
  },
  {
    address1: "101 Mug Ave.",
    address2: "Unit 12",
    city: "Butte",
    postalcode: 12345,
    state: "CA",
    country: "USA",
    managername: "Alex",
    managerphone: "(123)456-7890",
    managerhours: "8am - 5pm M-F",
  },
  {
    address1: "666 Olympic Ave.",
    address2: "Apt. 213",
    city: "Butte",
    postalcode: 12345,
    state: "CA",
    country: "USA",
    managername: "Alex",
    managerphone: "(123)456-7890",
    managerhours: "8am - 5pm M-F",
  },
]

apartments.each do |apartments|
  Apartment.create(apartments)
end
